spring.application.name=the-commit-crew-auth
server.port=8080
management.endpoint.web.exposure.include=health

jwt.secret=${JWT_SECRET:your-secret-key-min-32-chars}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh_expiration=${JWT_REFRESH_EXPIRATION:604800000}